rct/urls.py
from django.contrib import admin
from django.urls import path, include
from app.views import *
from django.contrib.auth.views import LoginView, LogoutView
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing, name='landing'),
    path('home/', home, name='home'),
    path('sewakan/',sewakan, name='sewakan'),
    path('status/', status_sewa, name='status'),
    path('my/', my_item, name='my'),
    path('masuk/', MyLoginView.as_view(), name='masuk'),
    path('keluar/', LogoutView.as_view(next_page='masuk'),name='keluar'),
    path('daftar/', daftar, name='daftar'),
    path('my/ubah/<int:id_alat>', ubah_my_item, name="ubah"),
    path('my/hapus/<int:id_alat>', hapus_my_item, name="hapus"),
    path('sewa/<int:id_alat>', halaman_sewa, name="halaman_sewa"),
    path('alat/<int:id_alat>/', sewa, name="sewa"),
    path('status/', status_sewa, name='status'),
    path('selesai/<int:sewa_id>', selesai, name='selesai'),
    path('profil/', profil, name='profil'),
    path('about/', about, name='about'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from djongo import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model
from django.core.validators import MaxValueValidator, MinValueValidator 


class User(AbstractUser):
    hp = models.CharField(max_length=14)
    foto = models.ImageField(default="profil/default-profil.png",null=True, blank=True, upload_to="profil/")


    def __str__(self):
        return self.username

class Alat(models.Model):
    User = get_user_model()
    ctype = (
        ('Jam', 'Jam'),
        ('Hari', 'Hari'),
    )

    nama_alat = models.CharField(max_length=25)
    harga = models.IntegerField(validators=[MinValueValidator(1000), MaxValueValidator(25000000)])
    durasi = models.CharField(max_length=20, choices=ctype, default="Hari")
    keterangan = models.TextField(blank=True, max_length=255)
    tersedia = models.BooleanField(default=True)
    gambar = models.ImageField(default="img/default-alat.jpg", null=True, blank=True, upload_to="img/")
    pemilik = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.nama_alat



class Penyewaan(models.Model):
    User = get_user_model()
    durasi = models.IntegerField()
    waktu_kembali = models.DateTimeField(auto_now=False, auto_now_add=False)
    total_harga = models.IntegerField()
    alat = models.ForeignKey(Alat, on_delete=models.CASCADE)
    penyewa = models.ForeignKey(User, on_delete=models.CASCADE,related_name='penyewa')
    pemilik = models.ForeignKey(User, on_delete=models.CASCADE,related_name='pemilik')

app/templates/about.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv = "refresh" content = "135; url = {% url 'home' %}" />
    <link href="{% static 'images/favicon.ico' %}" rel="icon">
    <title>RCT - About</title>
</head>
<body>
    <video autoplay loop id="myVideo">
        <source src="https://res.cloudinary.com/django-rct/video/upload/v1621323095/media/video/30_jqbssp.mp4" type="video/mp4">
    </video>
<div class="container">
    <div  id="a" class="title">
         <code >Rental of Cleaning Tools</code>
        <p id="b"> <strong><a href="{% url 'home' %}">RCT</a></strong> merupakan sebuah sistem penyewaan yang dibuat khusus untuk peralatan kebersihan. <br> <br>
            Pengguna dapat mencari peralatan kebersihan
            atau menyewakan peralatan kebersihan yang mereka miliki.</p>
            <hr>
            <p id="c">Website ini dibuat untuk menyelesaikan Mata Kuliah Proyek Perangkat Lunak 2021.</p>
            <!-- <p id="clock">-</p> -->
    </div>
</div>
        <audio autoplay>
            <!-- <source src="{% static 'audio/apex.mp3' %}" type="audio/mpeg"> -->
            <source src="https://res.cloudinary.com/django-rct/video/upload/v1621521453/media/w5h6greogwkvbyz2nmwn.mp3" type="audio/mpeg">
        </audio>
</body>
    
</html>
<span id="inf">Informatika - USK</span>

<style>
@import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@1,900&display=swap');
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;600&display=swap');

*{
    /* font-family: 'Montserrat', sans-serif; */
    font-family: 'Poppins', sans-serif;
    color: rgb(145, 224, 18);
    box-sizing: border-box;
}

#inf{
    color: rgb(206, 157, 24);
}

#myVideo {
    animation: video 1.5s;
    position: fixed;
    left: 0;
    top: 0;
}

clock{
    /* animation-delay: 20s; */
    animation: video 30s;
}
@media screen and (min-width:1280px) {
#myVideo {
    position: fixed;
    left: 0;
    top: 0;
    width: 120%;
}

}
video{
    object-fit: cover;
}

#a{
    animation: transitionIn 1s;
    /* animation-delay: 0s; */
}


#b{
    animation: transitionIn 2.5s;
}

#c{
    font-size: 10px;
    animation: transitionIn 6s;
}

p{
    /* animation: transitionIn 3s; */
    font-size:14px;
    margin-right: 5px;
    color: rgb(233, 250, 233);
}

hr{
    animation: transitionIn 4s;
    max-width: 50vh;
    margin: 0px;
}

br{
    display: block;
    line-height: 10px;
}
html{

/* background: url(/static/images/usk.png); */
/* background: rgba(211, 224, 17, 0.5); */
/* background-image:url(/static/images/usk.png); */
background-repeat: no-repeat;
background-size: contain;
background-position: center;
background-attachment: fixed;
}

code{
    padding-top: 10px;
    font-style: italic;
    font-size: 2rem;
}

.container{
    animation: video 3s;
    background-color: rgba(0, 0, 0, 0.5);
    position: relative;
    border-radius: 10px;
    width: 50%;

}

.title{
    padding: 5px;
    margin-top: 5vh;
    margin-left: 3vw;
}

body{
    height: 100%;
}

    
@media screen and (max-width:430px) {

    .container{
        position: relative;
        padding: 1rem;
        width:100%;
        height: 100%;
        /* background-color: rgba(4, 5, 56, 0.8); */
        background-color: rgba(0, 0, 0, 0.7);
        border-radius: 8px;
    }

    #myVideo {

        position: fixed;
        left: -300px;
        top:0;
        width:320%;
    }



}

@keyframes transitionIn{
    from{
        opacity: 0;
        transform: translateX(-200px);
        
    }
    to{
        opacity: 1;
        transform: translateX(0);

    }
}
@keyframes video{
    from{
        opacity: 0;
        
    }
    to{
        opacity: 1;

    }
}

@keyframes fade-r{
    from{
        opacity: 1;
        
    }
    to{
        opacity: 0;

    }
}
</style>

app/templates/about_local.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'images/favicon.ico' %}" rel="icon">
    <title>RCT - About</title>
</head>
<body>
    <video autoplay muted loop id="myVideo">
        <!-- <source src="{% static 'audio/bg-spark.mp4' %}" type="video/mp4"> -->
        <source src="{% static 'video/bg-spark.mp4' %}" type="video/mp4">
    </video>
<div class="container">
    <div  id="a" class="title">
         <code >Rental of Cleaning Tools
        </code>
        <p id="b"> <strong><a href="{% url 'home' %}">RCT</a></strong> merupakan sebuah sistem penyewaan yang dibuat khusus untuk peralatan kebersihan. <br> <br>
            Pengguna dapat mencari peralatan kebersihan
            atau menyewakan peralatan kebersihan yang mereka miliki.</p>
            <hr>
            <p id="c">Website ini dibuat untuk menyelesaikan Mata Kuliah Proyek Perangkat Lunak 2021.</p>
            <!-- <p id="clock">-</p> -->
            <!-- <audio autoplay>
                <source src="{% static 'audio/apex.mp3' %}" type="audio/mpeg">
            </audio> -->
        </div>
    </div>
    {% include 'layout/script.html' %}
</body>

</html>
<span id="inf">Informatika - USK</span>

<style>
@import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@1,900&display=swap');
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;600&display=swap');

*{
    /* font-family: 'Montserrat', sans-serif; */
    font-family: 'Poppins', sans-serif;
    color: rgb(206, 157, 24);
    box-sizing: border-box;
}

#inf{
    color: rgb(206, 157, 24);
}

#myVideo {
    animation: video 5s;
    position: fixed;
    left: 0;
    top: 0;
}

#clock{
    /* animation-delay: 20s; */
    animation: video 30s;
}
@media screen and (min-width:1280px) {
#myVideo {
    position: fixed;
    left: 0;
    top: 0;
    width: 120%;
}

}
video{
    object-fit: cover;
}

#a{
    animation: transitionIn 1s;
    /* animation-delay: 0s; */
}


#b{
    animation: transitionIn 2.5s;
}

#c{
    font-size: 10px;
    animation: transitionIn 6s;
}

p{
    /* animation: transitionIn 3s; */
    font-size:14px;
    margin-right: 5px;
    color: rgb(233, 250, 233);
}

hr{
    animation: transitionIn 4s;
    max-width: 50vh;
    margin: 0px;
}

br{
    display: block;
    line-height: 10px;
}


code{
    padding-top: 10px;
    font-style: italic;
    font-size: 2rem;
}

.container{
    background-color: rgba(0, 0, 0, 0.5);
    position: relative;
    border-radius: 10px;
    width: 50%;

}

.title{
    padding: 5px;
    margin-top: 5vh;
    margin-left: 3vw;
}

body{
    height: 100%;
}

    
@media screen and (max-width:411px) {

    .container{
        position: relative;
        padding: 1rem;
        width:100%;
        height: 100%;
        /* background-color: rgba(4, 5, 56, 0.8); */
        background-color: rgba(0, 0, 0, 0.7);
        border-radius: 8px;
    }

    #myVideo {
        position: fixed;
        left: -300px;
        top:0;
        width:320%;
    }


    html{
        left:0;
        top:0;
    }
}

@keyframes transitionIn{
    from{
        opacity: 0;
        transform: translateX(-200px);
        
    }
    to{
        opacity: 1;
        transform: translateX(0);

    }
}
@keyframes video{
    from{
        opacity: 0;
        
    }
    to{
        opacity: 1;

    }
}

@keyframes fade-r{
    from{
        opacity: 1;
        
    }
    to{
        opacity: 0;

    }
}
</style>

app/templates/home.html
{% extends 'base.html' %}
{%load static %}

{% block title %}
    <title>RCT</title>
{% endblock %}

{% block content %}
{% if tools  %}
<small class="d-flex justify-content-center mb-4 alert bg-green-secondary text-success ">Daftar alat kebersihan yang dapat disewa</small>
{%else%}
<small class="d-flex justify-content-center mb-4 alert bg-green-secondary text-pink ">Belum ada alat kebersihan yang dapat disewa</small>
{% endif %}
<div class="container my-3">
    <div class="row justify-content-center">
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'info' %} 
                <small class="text-center alert alert-warning my-4">
                    {{ message }}. <a class="" href="{% url 'profil' %}"> <strong> Lengkapi Profil</strong></a>
                </small>
                {% elif message.tags == 'success' %} 
                <small class=" w-100 text-success text-center alert alert-success m-1">{{ message }}. Buka <a href="{%url 'status'%} "> Status Sewa </a> untuk melihat detail.</small>
                <!-- <hr> -->
                {% endif %}
            {% endfor %}
        {% endif %}

        {% for tool in tools %}
        <!-- <div class="col-9 col-md-4 col-lg-3 my-4 w-250" id="alats"> -->
        <div class="my-4 w-250" id="alats">
            <a href="{% url 'halaman_sewa' tool.id %}">

                <div class="card">
                    <img id="alat" style="height: 220px;" src="{% if tool.gambar.url == 'https://res.cloudinary.com/django-rct/image/upload/v1/media/null' %} https://res.cloudinary.com/django-rct/image/upload/v1621320430/media/img/default-alat.jpg {% else %}  {{ tool.gambar.url }} {% endif %}" alt="{{  tool.gambar }}">
                    {%if tool.tersedia %}   
                    <div class="btn btn-outline-success">Tersedia</div>
                    {%else%} 
                    <div class="btn btn-outline-warning">Tidak Tersedia</div>
                    {%endif%}
                    {%if tool.pemilik_id == user.id %}   
                    <div class="btn btn-outline-primary">Milik Anda</div>
                    {%endif%}
                    <div style="height: 160px;" class="card-body text-center text-white bg-green-primary p-3">
                      <h5 class="card-title">{{ tool.nama_alat }}</h5>
                      <p class="card-text">Rp. {{ tool.harga }} / {{ tool.durasi }} </p>
                      <button class="btn bg-green-secondary text-dark">LIHAT</button>
                    </div>
                  </div>
            </a>
        </div>

    {% endfor %}
    </div>
</div>
{% endblock %}

app/templates/index.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  {% if user.is_authenticated %}
  <meta http-equiv="refresh" content="0; url={% url 'home' %}">
  {% endif %}

  <title>Rental of Cleaning Tools - RCT</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link rel="icon" href="{% static 'images/favicon.ico' %}"/>
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="rapple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  {% include 'layout/style.html' %} 


  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center">
    <div class="container d-flex justify-content-between align-items-center">

      <div class="logo">
        <h1><a href="{% url 'landing' %}">RCT</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="{% static 'assets/img/logo.png" alt="" class="img-fluid"></a>-->
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link active" href="{% url 'masuk' %}">Masuk</a></li>
          <!-- <li><a class="nav-link active" href="{% url 'about' %}">About</a></li> -->
          
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

  <!-- ======= Hero Section ======= -->
  <section class="hero-section" id="hero">

    <div class="wave">

      <svg width="100%" height="355px" viewBox="0 0 1920 355" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
        <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
          <g id="Apple-TV" transform="translate(0.000000, -402.000000)" fill="#FFFFFF">
            <path d="M0,439.134243 C175.04074,464.89273 327.944386,477.771974 458.710937,477.771974 C654.860765,477.771974 870.645295,442.632362 1205.9828,410.192501 C1429.54114,388.565926 1667.54687,411.092417 1920,477.771974 L1920,757 L1017.15166,757 L0,757 L0,439.134243 Z" id="Path"></path>
          </g>
        </g>
      </svg>

    </div>

    <div class="container">
      <div class="row align-items-center">
        <div class="col-12 hero-text-image">
            <div class="col-lg-8 text-center text-lg-start">
              <h1 data-aos="fade-right">Welcome to RCT</h1>
              <p data-aos-delay="100" data-aos="fade-right">We connect society with the environtment</p>
              <p data-aos="fade-right" data-aos-delay="200" data-aos-offset="-500"><a href="{% url 'daftar' %}" class="btn btn-outline-white">DAFTAR</a></p>
            </div>
        </div>
      </div>
    </div>

  </section><!-- End Hero -->

  <main id="main">

    <!-- ======= Home Section ======= -->
    <section class="section">
      <div class="container">

        <div class="row justify-content-center text-center mb-5">
          <div class="col-md-5" data-aos="fade-up">
            <h2 class="section-heading">Bersih - Bersih Jadi Lebih Mudah</h2>
          </div>
        </div>

        <div class="row">
          <div class="col-md-4" data-aos="fade-up" data-aos-delay="">
            <div class="feature-1 text-center">
              <div class="wrap-icon icon-1">
                <i class="bi bi-box-seam"></i>
              </div>
              <h3 class="mb-3">Sewa</h3>
              <p>Sewa peralatan kebersihan yang Anda perlu.</p>
            </div>
          </div>
          <div class="col-md-4" data-aos="fade-up" data-aos-delay="100">
            <div class="feature-1 text-center">
              <div class="wrap-icon icon-1">
                <i class="bi bi-eject-fill"></i>
              </div>
              <h3 class="mb-3">Sewakan</h3>
              <p>Sewakan peralatan kebersihan yang Anda punya.</p>
            </div>
          </div>
          <div class="col-md-4" data-aos="fade-up" data-aos-delay="200">
            <div class="feature-1 text-center">
              <div class="wrap-icon icon-1">
                <i class="bi bi-hourglass-split"></i>
              </div>
              <h3 class="mb-3">Status Penyewaan</h3>
              <p>Lihat status penyewaan dari peralatan yang sedang Anda sewa atau sewakan.
              </p>
            </div>
          </div>
        </div>

      </div>
    </section>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

app/templates/myitem.html
{% extends 'base.html' %}

{% block title %}
    <title>RCT - MyItem</title>
{% endblock %}
{% block content %}
{% if my_items %}
<small class="d-flex justify-content-center mb-4 alert bg-green-secondary text-success ">Daftar alat kebersihan yang Anda sewakan</small>
{%else%}
<small class="d-flex justify-content-center mb-4 alert bg-green-secondary text-pink ">Belum ada alat kebersihan yang Anda sewakan</small>
{% endif %}
<div class="container-fluid">
<div class="d-flex justify-content-center">
<div class="table-responsive">
  <table class="table table-bordered ">
    <thead>
      <tr class="text-center">
        <th>Nama Barang</th>
        <th>Durasi Penyewaan</th>
        <th>Harga Per Durasi</th>
        <th>Status</th>
        <!-- <th>Disewa Oleh</th> -->
        <th colspan="2">Aksi</th>
    </tr>
    </thead>


    {% for my in my_items %}
    <tbody>
          <tr>
              <td>{{ my.nama_alat }} </td>
              <td>{{ my.durasi }} </td>
              <td>Rp {{ my.harga }} </td>
              <!-- <td class="text-center">{% if my.tersedia %} <i class="fs-4 text-success bi bi-check"></i>  {%else%} <i class="fs-4 text-warning bi bi-x-circle-fill"></i> {%endif%}</td> -->
              <td class="">{% if my.tersedia %} <code class="text-success ">Tersedia</code>  {%else%} <code class="text-warning">Sedang Disewa</code> {%endif%}</td>

              <!-- <td class="">{{ sewa.penyewa.first_nama }} - {{ sewa.penyewa.hp }}</td> -->
              
              <td class="text-center">
                  <a href="{% url 'ubah' my.id %}" class="btn  btn-sm bg-green-primary text-white "><i class=" bi bi-pencil-square"></i></a>
              </td>
                <td class="text-center">
                  <button class="btn btn-sm btn-danger {% if not my.tersedia %} disabled {%endif%}"  type="button" class="btn btn-primary" data-toggle="modal" data-target="#hapus-{{my.id}}">
                    <i class="bi bi-trash"></i>
                    </button>
                </td>
              <div class="modal fade" id="hapus-{{my.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Hapus</h5>
                        <button type="button" class="close btn btn-outline-secondary" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                        Hapus item <strong> {{ my.nama_alat | upper }}</strong>?
                      </div>
                      <div class="modal-footer">
                          <a href = "{% url 'hapus' my.id %}" class="btn btn-danger">Hapus</a>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                      </div>
                    </div>
                  </div>
                </div>
          </tr>

        </tbody>
          {% endfor %}
  </table>
</div>
</div>
</div>

{% endblock %}

app/templates/sewa.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>RCT - Sewa</title>
{% endblock %}

{% block content %}

<div class="container p-4">
    <div class="row justify-content-center">
        {% for msg in messages %}
        {%if msg.tags == 'success' %}
        <small class="d-flex justify-content-center text-success text-center alert alert-success m-1">{{ msg }}</small>
        <hr>
        {%endif%}
        {%endfor%}
        <div class="col-12 col-md-7 col-lg-6  p-2">
            <div class="card py-2">
                <img class="h-400" id="img-sewa" src="{% if tool.gambar.url == 'https://res.cloudinary.com/django-rct/image/upload/v1/media/null' %} https://res.cloudinary.com/django-rct/image/upload/v1621320430/media/img/default-alat.jpg {% else %}  {{ tool.gambar.url }} {% endif %}"" alt="{{  tool.gambar }}">
                <!-- <img style="height: 400px;" src="/media/img/default.jpg" alt="{{  tool.gambar }}"> -->
            </div>
        </div>
        <div class="col-12  col-md-5 col-lg-4 p-2">
            <h2>{{ tool.nama_alat }}</h2>
            <p><strong>Keterangan</strong><br> {{ tool.keterangan }} </p>
            <p><strong>Pemilik</strong><br> <a href="{{ tool.pemilik.foto.url }}"> {{ tool.pemilik.first_name }} {{ tool.pemilik.last_name }}</a> - {{ tool.pemilik.hp }} </p>
            <p> <strong>Harga per {{ tool.durasi }}</strong><br> Rp {{ tool.harga }} </p>
            <form action="{% url 'sewa' tool.id %}" method="POST" class="mt-4">
                {% csrf_token %}
                <label for="id_durasi"><strong>Masukkan Durasi Penyewaan</strong> ({{ tool.durasi }})</label>
                <div class="d-flex">

                    <input type="number" min="1" max="30" name="durasi" class="form-control mr-3" value="1" required="" id="id_durasi" style="width:100px; margin-right: 14px;">
                    <button class="btn bg-green-primary text-white {%if not tool.tersedia %} disabled {%endif%}">Sewa Sekarang</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/sewakan.html
{% extends 'base.html' %}

{% block title %}
    <title>RCT - Sewakan Peralatan</title>
{% endblock %}

{% block content %}
<small class="d-flex justify-content-center mb4 alert bg-green-secondary text-success ">Sewakan alat kebersihan yang Anda miliki</small>
<div class="container">
    <div class="row justify-content-center ">
        <div class="w-300">
            {% if pesan %}
            <small class="d-flex justify-content-center text-success text-center alert alert-success m-1">{{ pesan }}</small>
            <hr>
            {% endif %}
            <form action="/sewakan/" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for f in form %}
                    {{ f.label }}
                    <p>{{ f }}</p>
                    <code class="text-danger">{{f.errors}}</code>

                {% endfor %}

                <button type="submit" class="w-100 btn bg-green-primary mt-2 mb-5 text-white">Sewakan</button>
            </form>
        </div>
    </div>
</div>


{% endblock %}

app/templates/status.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>RCT - Status Penyewaan</title>
{% endblock %} 

{% block content %}
{% if penyewaan %}
<small class="d-flex justify-content-center mb-4 alert bg-green-secondary text-success ">Daftar peralatan yang sedang dalam penyewaan</small>
{%else%}
<small class="d-flex justify-content-center mb-4 alert bg-green-secondary text-pink ">Anda belum melakukan penyewaan</small>
{% endif %}
<!-- <div class="container"> -->
  
<div class="container-fluid">
  <div class="d-flex justify-content-center">
    <div class="table-responsive">
      <table class="table-bordered table">
        <thead>
          <tr class="text-center">
            <th scope="col">ID</th>
            <th scope="col">Nama Alat</th>
            <th scope="col">Pemilik Alat</th>
            <th scope="col">Durasi Sewa</th>
            <th scope="col">Total Harga</th>
            <th scope="col">Waktu Pengembalian</th>
            <th scope="col">Disewa oleh</th>
            <th scope="col">Aksi</th>
        </tr>
        </thead>


        <tbody>
        {% for sewa in penyewaan %}
              <tr>
                <th scope="row">{{ sewa.id }}</th>
                  <td><a href="{% url 'halaman_sewa' sewa.alat_id %}">{{ sewa.alat.nama_alat }} </a></td>
                  <td>{% if sewa.pemilik.id == user.id %} <strong class="text-pink">Anda{%else%} <a href="{{ sewa.penyewa.foto.url }}"> {{ sewa.penyewa.first_name }} {{ sewa.penyewa.last_name }}</a> - {{ sewa.pemilik.hp }} {%endif%} </td>
                  <td>{{ sewa.durasi }} Jam  </td>
                  <td>Rp {{sewa.total_harga }} </td>
                  <td>{{ sewa.waktu_kembali }}</td>
                  <td>{% if sewa.penyewa.id == user.id %} <strong class="text-pink">Anda{%else%}<a href="{{ sewa.penyewa.foto.url }}"> {{ sewa.penyewa.first_name }} {{ sewa.penyewa.last_name }}</a> - {{ sewa.penyewa.hp }} {%endif%} </td>
                  <td class="text-center">
                      <a href="{% url 'selesai' sewa.id %}" class="btn btn-sm btn-outline-dark">Tandai Selesai</a>
                  </td>

              </tr>

              {% endfor %}
            </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}